<?php

namespace ContainerYuiWOxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LogNSZSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LogNSZS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LogNSZS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.LogNSZS.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.LogNSZS": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'manager' => '?',
            'produit' => 'App\\Entity\\Product',
        ]);
    }
}
