<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYuiWOxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYuiWOxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYuiWOxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYuiWOxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYuiWOxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'YuiWOxv',
    'container.build_id' => '7bce43c6',
    'container.build_time' => 1605980278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYuiWOxv');
